name = "LinearEcon"
uuid = "b53dc4d5-51bf-47cc-b23f-9debdb032eae"
authors = ["liviomaya <liviomaya@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
